:project_name: Name des Projekts
:toc: left
:numbered:
= Pflichtenheft __{project_name}__

[options="header"]
[cols="1, 1, 1, 1, 4"]
|===
|Version | Status      | Bearbeitungsdatum   | Autoren(en) |  Vermerk
|0.1     | In Arbeit   | 10.10.2021          | Autor       | Initiale Version
|===

== Inhaltsverzeichnis
Dieses Dokument benötigt ein Inhaltsverzeichnis. Es existieren mehrere Einbindungsmöglichkeiten.

== Zusammenfassung
Eine kurze Beschreibung des Dokuments. Wenige Absätze.

== Aufgabenstellung und Zielsetzung
Text aus Aufgabenstellung kopieren und ggfs. präzisieren.
Insbesondere ergänzen, welche Ziele mit dem Abschluss des Projektes erreicht werden sollen.

== Produktnutzung
In welchem Kontext soll das System später genutzt werden? Welche Rahmenbedingungen gelten?
Zusätzlich kurze Einleitung für fachfremde Personen

== Interessensgruppen (Stakeholders)
Welche realen und juristischen Personen(-gruppen) haben Einfluss auf die Anforderungen im Projekt?

== Systemgrenze und Top-Level-Architektur

=== Kontextdiagramm
Das Kontextdiagramm zeigt das geplante Software-System in seiner Umgebung. Zur Umgebung gehören alle Nutzergruppen des Systems und Nachbarsysteme. Die Grafik kann auch informell gehalten sein. Überlegen Sie sich dann geeignete Symbole. Die Grafik kann beispielsweise mit Visio erstellt werden. Wenn nötig, erläutern Sie diese Grafik.

=== Top-Level-Architektur
Dokumentieren Sie ihre Top-Level-Architektur mit Hilfe eines Komponentendiagramm.

== Anwendungsfälle

=== Akteure

Akteure sind die Benutzer des Software-Systems oder Nachbarsysteme, welche darauf zugreifen. Dokumentieren Sie die Akteure in einer Tabelle. Diese Tabelle gibt einen Überblick über die Akteure und beschreibt sie kurz. Die Tabelle hat also mindestens zwei Spalten (Akteur Name und Kommentar).
Weitere relevante Spalten können bei Bedarf ergänzt werden.

// See http://asciidoctor.org/docs/user-manual/#tables
[options="header"]
[cols="1,4"]
|===
|Name |Beschreibung
|...  |...
|===

=== Überblick Anwendungsfalldiagramm
Anwendungsfall-Diagramm, das alle Anwendungsfälle und alle Akteure darstellt

=== Anwendungsfallbeschreibungen
Dieser Unterabschnitt beschreibt die Anwendungsfälle. In dieser Beschreibung müssen noch nicht alle Sonderfälle und Varianten berücksichtigt werden. Schwerpunkt ist es, die wichtigsten Anwendungsfälle des Systems zu finden. Wichtig sind solche Anwendungsfälle, die für den Auftraggeber, den Nutzer den größten Nutzen bringen.
Für komplexere Anwendungsfälle ein UML-Sequenzdiagramm ergänzen.
Einfache Anwendungsfälle mit einem Absatz beschreiben.
Die typischen Anwendungsfälle (Anlegen, Ändern, Löschen) können zu einem einzigen zusammengefasst werden.

== Funktionale Anforderungen

=== Muss-Kriterien
Was das zu erstellende Programm auf alle Fälle leisten muss.

=== Kann-Kriterien
Anforderungen die das Programm leisten können soll, aber für den korrekten Betrieb entbehrlich sind.

== Nicht-Funktionale Anforderungen

=== Qualitätsziele

Dokumentieren Sie in einer Tabelle die Qualitätsziele, welche das System erreichen soll, sowie deren Priorität.

=== Konkrete Nicht-Funktionale Anforderungen

Beschreiben Sie Nicht-Funktionale Anforderungen, welche dazu dienen, die zuvor definierten Qualitätsziele zu erreichen.
Achten Sie darauf, dass deren Erfüllung (mindestens theoretisch) messbar sein muss.

== GUI Prototyp

In diesem Kapitel soll ein Entwurf der Navigationsmöglichkeiten und Dialoge des Systems erstellt werden.
Idealerweise entsteht auch ein grafischer Prototyp, welcher dem Kunden zeigt, wie sein System visuell umgesetzt werden soll.
Konkrete Absprachen - beispielsweise ob der grafische Prototyp oder die Dialoglandkarte höhere Priorität hat - sind mit dem Kunden zu treffen.

=== Überblick: Dialoglandkarte
Erstellen Sie ein Übersichtsdiagramm, das das Zusammenspiel Ihrer Masken zur Laufzeit darstellt. Also mit welchen Aktionen zwischen den Masken navigiert wird.
//Die nachfolgende Abbildung zeigt eine an die Pinnwand gezeichnete Dialoglandkarte. Ihre Karte sollte zusätzlich die Buttons/Funktionen darstellen, mit deren Hilfe Sie zwischen den Masken navigieren.

=== Dialogbeschreibung
Für jeden Dialog:

1. Kurze textuelle Dialogbeschreibung eingefügt: Was soll der jeweilige Dialog? Was kann man damit tun? Überblick?
2. Maskenentwürfe (Screenshot, Mockup)
3. Maskenelemente (Ein/Ausgabefelder, Aktionen wie Buttons, Listen, …)
4. Evtl. Maskendetails, spezielle Widgets

== Datenmodell

=== Überblick: Klassendiagramm
UML-Analyseklassendiagramm

=== Klassen und Enumerationen
Dieser Abschnitt stellt eine Vereinigung von Glossar und der Beschreibung von Klassen/Enumerationen dar. Jede Klasse und Enumeration wird in Form eines Glossars textuell beschrieben. Zusätzlich werden eventuellen Konsistenz- und Formatierungsregeln aufgeführt.

// See http://asciidoctor.org/docs/user-manual/#tables
[options="header"]
|===
|Klasse/Enumeration |Beschreibung |
|…                  |…            |
|===

== Akzeptanztestfälle
Mithilfe von Akzeptanztests wird geprüft, ob die Software die funktionalen Erwartungen und Anforderungen im Gebrauch
erfüllt.
Diese sollen und können aus den Anwendungsfallbeschreibungen und den UML-Sequenzdiagrammen abgeleitet werden.
D.h., pro (komplexen) Anwendungsfall gibt es typischerweise mindestens ein Sequenzdiagramm (, welches ein
Szenarium beschreibt). Für jedes Szenarium sollte es einen Akzeptanztestfall geben. Listen Sie alle Akzeptanztestfälle in tabellarischer Form auf.
Jeder Testfall soll mit einer ID versehen werde, um später zwischen den Dokumenten (z.B. im Test-Plan) referenzieren zu können.

:Pre: Precondition(s)
:Event: Event
:Result: Expected Result


[[AT001]]
[cols="1h, 4"]
|===
|ID            |<<AT001>>
|Use Case      |Admin
|{Pre}        a|
- The system has existing admin.
- A dummy-order is accepted.
|{Event}      a|Admin logg in and look for finance-chart.
|{Result}     a|
- Finance-Chart exists.
- Profit is correct insert in chart.
|===

[[AT002]]
[cols="1h, 4"]
|===
|ID            |<<AT002>>
|Use Case      |Admin
|{Pre}        a|
- The system has existing admin.
- A dummy-employee exists.
|{Event}      a|Admin logg in and views the employee list.
|{Result}     a|
- The employee list is displayed-
- Dummy-employee is can been seen.
|===

[[AT003]]
[cols="1h, 4"]
|===
|ID            |<<AT003>>
|Use Case      |Admin
|{Pre}        a|
- The system has existing admin.
- A dummy-employee exists.
|{Event}      a|Admin logg in and deletes dummy-employee.
|{Result}     a|The dummy-employee is no longer in the list.
|===

[[AT004]]
[cols="1h, 4"]
|===
|ID            |<<AT004>>
|Use Case      |Admin
|{Pre}        a|
- The system has existing admin.
|{Event}      a|Admin logg in and adds a new employee with valid name, email, adress and password.
|{Result}     a|The new employee appears in the list.
|===

[[AT005]]
[cols="1h, 4"]
|===
|ID            |<<AT005>>
|Use Case      |Mitarbeiter
|{Pre}        a|
- The system has existing employee.
- A dummy-order exists.
|{Event}      a|The employee logg in and look at existing order-page.
|{Result}     a|The dummy-order is displayed correctly.
|===

[[AT006]]
[cols="1h, 4"]
|===
|ID            |<<AT006>>
|Use Case      |Mitarbeiter
|{Pre}        a|
- The system has existing employee.
- A dummy-customer exists.
|{Event}      a|The employee logg in and views the customer list
|{Result}     a|The customer is displayed correctly in the customer list.
|===

[[AT007]]
[cols="1h, 4"]
|===
|ID            |<<AT007>>
|Use Case      |Mitarbeiter
|{Pre}        a|
- The system has existing employee.
- A dummy-order exists.
|{Event}      a|The employee logg in and deletes a dummy orde.
|{Result}     a|The order is no longer found in the order list.
|===

[[AT008]]
[cols="1h, 4"]
|===
|ID            |<<AT008>>
|Use Case      |Mitarbeiter
|{Pre}        a|
- The system has existing employee.
- A dummy-order exists.
|{Event}      a|The employee logg in and confirms the dummy order.
|{Result}     a|The order is displayed as already paid.
|===

[[AT009]]
[cols="1h, 4"]
|===
|ID            |<<AT009>>
|Use Case      |Mitarbeiter
|{Pre}        a|
- The system has existing employee.
- A dummy-customer exists.
|{Event}      a|The employee logg in and deletes a dummy customer.
|{Result}     a|The customer is deleted successfully and the customer is no longer in the customer list.
|===

[[AT010]]
[cols="1h, 4"]
|===
|ID            |<<AT010>>
|Use Case      |Mitarbeiter
|{Pre}        a|- The system has existing employee.
|{Event}      a|The employee logg in and adds a new product with valid name, picture, stock, price and genre.
|{Result}     a|The product can be found in product list. 
|===

[[AT011]]
[cols="1h, 4"]
|===
|ID            |<<AT011>>
|Use Case      |Mitarbeiter
|{Pre}        a|
- The system has existing employee.
- A dummy-product exists.
|{Event}      a|The employee loggs in and remove the dummy-product.
|{Result}     a|Dummy-product no longer in product list.
|===

[[AT012]]
[cols="1h, 4"]
|===
|ID            |<<AT012>>
|Use Case      |Mitarbeiter
|{Pre}        a|
- The system has existing employee.
- A dummy-product book exists.
|{Event}      a|The employee deletes genre of book.
|{Result}     a|The product is furthermore in the product list.
|===

[[AT013]]
[cols="1h, 4"]
|===
|ID            |<<AT013>>
|Use Case      |Kunde
|{Pre}        a|
- The system has existing customer.
- A dummy-product exists.
|{Event}      a|The customer loggs in and add dummy-product with count 1 to cart.
|{Result}     a|The item is displayed correct in cart.
|===

[[AT014]]
[cols="1h, 4"]
|===
|ID            |<<AT014>>
|Use Case      |Kunde
|{Pre}        a|
- The system has existing customer.
- A dummy-product of count 5 exists.
- The dummy-product is add with count 1 to cart
|{Event}      a|The customer loggs in and removes the dummy item from the cart.
|{Result}     a|No item is displayed in the cart
|===

[[AT015]]
[cols="1h, 4"]
|===
|ID            |<<AT015>>
|Use Case      |Without Permissions
|{Pre}        a|
- The system has existing customer.
- A dummy-product exists.
|{Event}      a|The customer searches for the title of dummy-product in seach ad.
|{Result}     a|The book is displayed as correct result of search.
|===


== Glossar
Sämtliche Begriffe, die innerhalb des Projektes verwendet werden und deren gemeinsames Verständnis aller beteiligten
Stakeholder essenziell ist, sollten hier aufgeführt werden.
Insbesondere Begriffe der zu implementierenden Domäne wurden bereits beschrieben, jedoch gibt es meist mehr Begriffe, die einer Beschreibung bedürfen. +
Beispiel: Was bedeutet "Kunde"? Ein Nutzer des Systems? Der Kunde des Projektes (Auftraggeber)?

== Offene Punkte
Offene Punkte werden entweder direkt in der Spezifikation notiert. Wenn das Pflichtenheft zum finalen Review vorgelegt wird, sollte es keine offenen Punkte mehr geben.
